### ISSUE TITLE
Docker setup step missing: Replicate the repo to the docker image again

### ISSUE THREAD

**Issue by tmangelmann** [SAP-samples/cloud-btp-cli-api-codejam#14]
Hi,

I noticed while in the codejam that I needed to execute some scripts from the github repo. However I couldn't find these in the $HOME/projects folder described in the exercise.

Perhaps another git clone could be included in the documentation (solved my issue), or alternatively the cloned repo could be part of the docker image.

Br
Toni

**Comment by qmacro** [comment]
Thanks again for the comment during the CodeJam. I've added a note to the container README highlighting that there's a bit of "Inception" here for those taking the container route:

- the outer clone to get to the `Dockerfile` to build the working environment image
- the inner clone, within the working environment, as part of Exercise 05

I want to avoid pre-cloning this repo into the working environment, because that would then mean that the instructions (between the Dev Space users and the container users) would then diverge a little.

**Comment by tmangelmann** [comment]
Glad I could contribute :-)
