### ISSUE TITLE
Exercise 7 Checking the access token and API base URL

### ISSUE THREAD

**Issue by jung-thomas** [SAP-samples/cloud-btp-cli-api-codejam#28]
https://github.com/SAP-samples/cloud-btp-cli-api-codejam/blob/main/exercises/07-core-services-api-call/README.md
With your new jq filtering skills, tease out these two values to have a look at them.

👉 First, have a look at the base URL:

`jq --raw-output .credentials.endpoints.entitlements_service_url cis-central-sk.json`

This doesn't work for me - I get null.  There is no credentials level in my cis-central-sk.json.  endpoints is the at the root.  I had to change the command. 

![image](https://user-images.githubusercontent.com/12159356/210431568-fbdd6618-53b5-4371-ba64-8fda8ff3e45e.png)

![image](https://user-images.githubusercontent.com/12159356/210431614-0292ea64-3d9a-44a6-865f-9ccc8a47bf7c.png)

![image](https://user-images.githubusercontent.com/12159356/210431795-a6c4a70a-1449-4dd4-89e9-e71753e9dea6.png)

**Comment by jung-thomas** [comment]
Same issue later in Exercise 9. I had to remove the credentials level of the json path for it to work.

**Comment by qmacro** [comment]
The cause of this is the same as for #27 - a difference in JSON output depending on whether `cf` version 7 or version 8 is used. BAS now uses version 8, so I've [modified the Dockerfile](https://github.com/SAP-samples/cloud-btp-cli-api-codejam/pull/31/files#diff-cc3b3db023efc81750e416e31d7a4b949db47a02683968e53761662b6138bced) to update the container image so that it matches this new version in BAS, and so that the exercise text and instructions can be the same (i.e. using `credentials` as the top level property).
